version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres14
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sga_test1_20241107.backup:/docker-entrypoint-initdb.d/sga_test1_20241107.backup
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    command: start-notebook.sh --NotebookApp.token=''